"""Initial migration

Revision ID: 16cba2ab357d
Revises:
Create Date: 2024-06-08 00:57:11.143621

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16cba2ab357d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE EXTENSION IF NOT EXISTS vector;
    """)
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS public.yappi_id_seq;
    """)
    op.create_table(
        "yappi",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("nextval('public.yappi_id_seq')"),
            nullable=False,
        ),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("face", sa.String(), nullable=True),
        sa.Column("tags_description", sa.String(), nullable=True),
        sa.Column("voise_description", sa.String(), nullable=True),
        sa.Column("image_description", sa.String(), nullable=True),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column(
            "embedding_description",
            pgvector.sqlalchemy.Vector(dim=384),
            nullable=True,
        ),
        sa.Column("create_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("face"),
        sa.UniqueConstraint("link"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("yappi", schema="public")
    # ### end Alembic commands ###
