"""timestamp, unique link

Revision ID: 5f7042139f2b
Revises: 6c1084106327
Create Date: 2024-06-04 03:20:27.713937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f7042139f2b"
down_revision: Union[str, None] = "6c1084106327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "yappi", ["link"], schema="public")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "yappi", schema="public", type_="unique")
    # ### end Alembic commands ###
