"""Initial migration

Revision ID: 6c1084106327
Revises:
Create Date: 2024-06-04 01:53:34.304656

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c1084106327"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE EXTENSION IF NOT EXISTS vector;
    """)
    op.execute("""
        CREATE SEQUENCE public.yappi_id_seq;
    """)
    op.create_table(
        "yappi",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("nextval('public.yappi_id_seq')"),
            nullable=False,
        ),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("deskr_tags", sa.String(), nullable=True),
        sa.Column("deskr_voise", sa.String(), nullable=True),
        sa.Column("desk_image", sa.String(), nullable=True),
        sa.Column("deck_full", sa.Text(), nullable=True),
        sa.Column(
            "desk_embedding",
            pgvector.sqlalchemy.Vector(dim=1024),
            nullable=True,
        ),
        sa.Column("create_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("pop", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("yappi", schema="public")
    # ### end Alembic commands ###
