"""Tags

Revision ID: e7fc81975d1d
Revises: 16cba2ab357d
Create Date: 2024-06-12 15:51:21.493764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7fc81975d1d"
down_revision: Union[str, None] = "16cba2ab357d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE SEQUENCE IF NOT EXISTS public.tag_id_seq;
    """
    )
    op.create_table(
        "tag",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("nextval('public.tag_id_seq')"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="public",
    )
    op.create_table(
        "yappi_tag",
        sa.Column("yappi_id", sa.BigInteger(), nullable=True),
        sa.Column("tag_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["public.tag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["yappi_id"],
            ["public.yappi.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("yappi_tag")
    op.drop_table("tag", schema="public")
    # ### end Alembic commands ###
