services:
  db:
    image: inferno681/pgvector:latest
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:89-1.2
    container_name: embeddings
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./data:/data
    environment:
      - MODEL_ID=intfloat/multilingual-e5-small
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  backend:
    image: inferno681/lcthackathon:latest
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  db_value:
