services:
  db:
    image: inferno681/pgvector:latest
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
    container_name: embeddings
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./data:/data
    environment:
      - MODEL_ID=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  backend:
    image: inferno681/lcthackathonapi:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - /usr/share/nginx/html/dist/:/usr/share/
      - /usr/share/nginx/html/:/app/media/
  frontend:
    image: tisavaco/hackaton-web
    depends_on:
      - backend
    volumes:
      - /usr/share/nginx/html/:/app/result_build/

volumes:
  db_value:
  redis_data:
