services:
  db:
    image: inferno681/pgvector:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret_password
  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:turing-1.2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8082:80"
    volumes:
      - ./data:/data
    environment:
      - MODEL_ID=intfloat/multilingual-e5-small
volumes:
  db_value:
